package org.hisp.dhis.jsontree;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tested generated by AI based on the specification of {@link Json5} I gave it.
 * Needed some cleanup/correction on the tricky cases that are not quote JSON5.
 *
 * @author AI with cleanup
 */
class Json5SpecTest {

    @Test
    void testStrings() {
      // Double‑quoted strings pass through unchanged
      assertEquals("\"Hello world\"", Json5.of("\"Hello world\"").toJson());

      // Single‑quoted strings: unescaped double quotes become single quotes
      assertEquals("\"Hello 'world'\"", Json5.of("'Hello \"world\"'").toJson());

      // Single‑quoted strings: escaped double quotes remain escaped double quotes
      assertEquals("\"She said \\\"Hi\\\"\"", Json5.of("'She said \\\"Hi\\\"'").toJson());

      // Mixed escapes
      assertEquals("\"Line1\\nLine2\"", Json5.of("'Line1\\nLine2'").toJson());

      // Strings with both quote types
      assertEquals("\"JSON \\\"string\\\" and 'quoted'\"",
          Json5.of("\"JSON \\\"string\\\" and 'quoted'\"").toJson());
      assertEquals("\"JSON \\\"string\\\" and 'quoted'\"",
          Json5.of("'JSON \\\"string\\\" and \"quoted\"'").toJson());
    }

    @Test
    void testKeys() {
      // Double‑quoted keys pass through
      assertEquals("{\"name\":42}", Json5.of("{\"name\":42}").toJson());

      // Single‑quoted keys: transformation same as strings
      assertEquals("{\"name\":42}", Json5.of("{'name':42}").toJson());
      assertEquals("{\"na'me\":42}", Json5.of("{'na\"me':42}").toJson()); // " becomes ' in output
      assertEquals("{\"na\\\"me\":42}", Json5.of("{'na\\\"me':42}").toJson());
    }

    @Test
    void testArrays() {
      // Simple arrays
      assertEquals("[1,2,3]", Json5.of("[1,2,3]").toJson());

      // Trailing comma allowed and removed
      assertEquals("[1,2,3 ]", Json5.of("[1,2,3,]").toJson());

      // Nested arrays
      assertEquals("[[1,2],[3,4]]", Json5.of("[[1,2],[3,4]]").toJson());
      assertEquals("[[1,2 ],[3,4 ] ]", Json5.of("[[1,2,],[3,4,],]").toJson());

      // Arrays with strings
      assertEquals("[\"a\",\"b\"]", Json5.of("['a',\"b\"]").toJson());
      assertEquals("[\"a\",\"b\" ]", Json5.of("['a','b',]").toJson());
    }

    @Test
    void testObjects() {
      // Simple object
      assertEquals("{\"a\":1,\"b\":2}", Json5.of("{\"a\":1,\"b\":2}").toJson());
      assertEquals("{\"a\":1,\"b\":2}", Json5.of("{'a':1,'b':2}").toJson());

      // Trailing comma allowed and removed
      assertEquals("{\"a\":1,\"b\":2 }", Json5.of("{\"a\":1,\"b\":2,}").toJson());
      assertEquals("{\"a\":1,\"b\":2 }", Json5.of("{'a':1,'b':2,}").toJson());

      // Nested objects
      assertEquals("{\"outer\":{\"inner\":42}}",
          Json5.of("{\"outer\":{\"inner\":42}}").toJson());
      assertEquals("{\"outer\":{\"inner\":42 } }",
          Json5.of("{'outer':{'inner':42,},}").toJson());

      // Mixed key quoting
      assertEquals("{\"a\":1,\"b\":2}", Json5.of("{\"a\":1,'b':2}").toJson());
    }

    @Test
    void testNumbers() {
      // Standard JSON numbers
      assertEquals("[0,-0,123,-123,123.456,-123.456,1e10,-1e-10,1.23e+5]",
          Json5.of("[0,-0,123,-123,123.456,-123.456,1e10,-1e-10,1.23e+5]").toJson());

      // Leading decimal point not allowed
      assertThrows(JsonFormatException.class, () -> Json5.of("[.5]"));
      // Trailing decimal point not allowed
      assertThrows(JsonFormatException.class, () -> Json5.of("[5.]"));
      // Hexadecimal not allowed
      assertThrows(JsonFormatException.class, () -> Json5.of("[0xFF]"));
    }

    @Test
    void testSpecialLiterals() {
      // Allowed: surrounded by whitespace (space becomes quotes)
      assertEquals("[1,\"NaN\",2]", Json5.of("[1, NaN, 2]").toJson());
      assertEquals("[\"NaN\"]", Json5.of("[ NaN ]").toJson());
      assertEquals("[\"Infinity\"]", Json5.of("[ Infinity ]").toJson());
      assertEquals("[\"-Infinity\"]", Json5.of("[ -Infinity ]").toJson());

      // Allowed: comma before literal, whitespace after
      assertEquals("[1,\"NaN\"]", Json5.of("[1, NaN ]").toJson());
      assertEquals("[1,\"Infinity\"]", Json5.of("[1, Infinity ]").toJson());
      assertEquals("[1,\"-Infinity\"]", Json5.of("[1, -Infinity ]").toJson());

      // Allowed: whitespace before literal, comma after
      assertEquals("[\"NaN\",2]", Json5.of("[ NaN, 2]").toJson());
      assertEquals("[\"Infinity\",2]", Json5.of("[ Infinity, 2]").toJson());
      assertEquals("[\"-Infinity\",2]", Json5.of("[ -Infinity, 2]").toJson());

      // Not allowed: no whitespace and no comma to leverage
      assertThrows(JsonFormatException.class, () -> Json5.of("[NaN]"));
      assertThrows(JsonFormatException.class, () -> Json5.of("[Infinity]"));
      assertThrows(JsonFormatException.class, () -> Json5.of("[-Infinity]"));
      assertThrows(JsonFormatException.class, () -> Json5.of("[1,NaN,2]")); // no spaces
    }

    @Test
    void testTrailingCommas() {
      // Arrays
      assertEquals("[]", Json5.of("[]").toJson());
      assertThrows(JsonFormatException.class, () -> Json5.of("[,]"));
      assertEquals("[1 ]", Json5.of("[1,]").toJson());
      assertEquals("[1,2 ]", Json5.of("[1,2,]").toJson());

      // Objects
      assertEquals("{}", Json5.of("{}").toJson());
      assertThrows(JsonFormatException.class, () -> Json5.of("{,}"));
      assertEquals("{\"a\":1 }", Json5.of("{\"a\":1,}").toJson());
      assertEquals("{\"a\":1,\"b\":2 }", Json5.of("{\"a\":1,\"b\":2,}").toJson());

      // Nested with trailing commas
      assertEquals("{\"arr\":[1,2 ] }", Json5.of("{\"arr\":[1,2,],}").toJson());
    }

    @Test
    void testMixedStructures() {
      String input = """
                {
                  'name': 'John "Doe"',
                  'bio': 'He said \\"Hello\\"',
                  'age': 42,
                  'tags': ['developer', 'json5-ish',],
                  'active': true,
                  'score': 98.6,
                  'special': NaN,
                  'inf': Infinity,
                }""";

      //language=JSON
      String expected = """
                {"name":"John 'Doe'","bio":"He said \\"Hello\\"","age":42,"tags":["developer","json5-ish"],"active":true,"score":98.6,"special":"NaN","inf":"Infinity"}""";

      // Remove whitespace for comparison (JSON can be compact)
      assertEquals(expected.replaceAll("\\s+", ""),
          Json5.of(input).toJson().replaceAll("\\s+", ""));
    }

    @Test
    void testWhitespace() {
      // Only allowed whitespace characters: space, tab, newline, carriage return
      assertEquals("[1,\t2]", Json5.of("[1,\t2]").toJson());
      assertEquals("[1,\n2]", Json5.of("[1,\n2]").toJson());
      assertEquals("[1,\r2]", Json5.of("[1,\r2]").toJson());

      // Form feed is not allowed
      assertThrows(JsonFormatException.class, () -> Json5.of("[1,\f2]"));
    }

    @Test
    void testComments() {
      assertEquals("[1,           2 ]", Json5.of("[1,/*before */2,]").toJson());
      assertEquals("[1,2            ]", Json5.of("[1,2 /*after */,]").toJson());
      assertEquals("[1,2 ]", Json5.of("[1,2,] //our array").toJson());
      assertEquals("[1,2 ]", Json5.of("[1,2,] /* our array */").toJson());
      assertEquals("[1,2 ]", Json5.of("[1,2,] /* our array */ /**/").toJson());
    }

    @Test
    void testInvalidSyntax() {
      // Unquoted object keys
      assertThrows(JsonFormatException.class, () -> Json5.of("{name:42}"));

      // Leading decimal point
      assertThrows(JsonFormatException.class, () -> Json5.of("[.5]"));

      // Trailing decimal point
      assertThrows(JsonFormatException.class, () -> Json5.of("[5.]"));

      // Hexadecimal numbers
      assertThrows(JsonFormatException.class, () -> Json5.of("[0xFF]"));

      // Just a comment is not allowed
      assertThrows(JsonFormatException.class, () -> Json5.of("// comment"));
      assertThrows(JsonFormatException.class, () -> Json5.of("/* comment */"));

      // Double quotes as delimiters for strings (already allowed, but test if mixing works)
      // Actually double quotes are allowed as delimiters, so this is valid:
      assertEquals("\"hello\"", Json5.of("\"hello\"").toJson());
    }
}
